/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICowSettlement,
  ICowSettlementInterface,
} from "../ICowSettlement";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "orderUid",
        type: "bytes",
      },
      {
        internalType: "bool",
        name: "signed",
        type: "bool",
      },
    ],
    name: "setPreSignature",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICowSettlement__factory {
  static readonly abi = _abi;
  static createInterface(): ICowSettlementInterface {
    return new utils.Interface(_abi) as ICowSettlementInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICowSettlement {
    return new Contract(address, _abi, signerOrProvider) as ICowSettlement;
  }
}
