/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type RecipientStruct = {
  chainId: BigNumberish;
  cycle: BigNumberish;
  wallet: string;
  amount: BigNumberish;
};

export type RecipientStructOutput = [
  BigNumber,
  BigNumber,
  string,
  BigNumber
] & { chainId: BigNumber; cycle: BigNumber; wallet: string; amount: BigNumber };

export interface ITokeRewardInterface extends utils.Interface {
  functions: {
    "claim((uint256,uint256,address,uint256),uint8,bytes32,bytes32)": FunctionFragment;
    "claimedAmounts(address)": FunctionFragment;
    "getClaimableAmount((uint256,uint256,address,uint256))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "claim",
    values: [RecipientStruct, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimedAmounts",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableAmount",
    values: [RecipientStruct]
  ): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimedAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableAmount",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ITokeReward extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITokeRewardInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claim(
      recipient: RecipientStruct,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimedAmounts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getClaimableAmount(
      recipient: RecipientStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  claim(
    recipient: RecipientStruct,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimedAmounts(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  getClaimableAmount(
    recipient: RecipientStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    claim(
      recipient: RecipientStruct,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    claimedAmounts(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getClaimableAmount(
      recipient: RecipientStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    claim(
      recipient: RecipientStruct,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimedAmounts(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getClaimableAmount(
      recipient: RecipientStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claim(
      recipient: RecipientStruct,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimedAmounts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getClaimableAmount(
      recipient: RecipientStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
